"""add_slot_label

Revision ID: 52d95e139330
Revises: 3fde069e96dc
Create Date: 2026-04-02 00:01:24.973468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d95e139330'
down_revision: Union[str, Sequence[str], None] = '3fde069e96dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('slot_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'slot_label')
    # ### end Alembic commands ###
